### ISSUE TITLE
Actividad 1. Mapa mental

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-1-mapa-mental-AdriHernandez-Martinez0863#1]
![Uploading Investigación Documental .jpeg…]()

**Comment by AdriHernandez-Martinez0863** [comment]
Actividad 1. Mapa mental
Adriana Hernandez Martinez    
Grupo: 1BS
![Investigación Documental ](https://user-images.githubusercontent.com/112270248/187830119-cf4c5faf-3567-4adb-822e-b448de093505.jpeg)

**Comment by Jaczibeth** [comment]
de 20% sacaste 18.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
